### ISSUE TITLE
Repo doesn't currently have a license

### ISSUE THREAD

**Issue by vprakash-seatgeek** [dougle/aws-vpn-tab-close#1]
Would it be possible to add a LICENSE file to this repo? It currently doesn't have one which technically defaults the code to "all rights reserved". I'm interested in forking your repo into my company's Git instance because it would be a really useful tool (I despise those AWS VPN tabs). Thanks!

**Comment by dougle** [comment]
@vprakash-seatgeek I've added a license so you can fork it as you wish.

A built version is already available in the webstore https://chromewebstore.google.com/detail/eeohkjpjmohadfbgaghdofdphnjhidfg?hl=en-GB
