### ISSUE TITLE
Security Review 

### ISSUE THREAD

**Issue by jishyuuu** [dougle/aws-vpn-tab-close#4]
Hey there, we were shown this web extension helpful to some of our developer team when they connect to their AWS VPN. I wanted to ask what access does this extension have such as reading web browser data, etc. I saw you had no published security docs, so decided to make an open issue to ask. If there's a better way to contact you about this, comment it and I'll reach out via your preferred way.

**Comment by dougle** [comment]
Hi @jishyuuu sorry for the late reply, this extension requires only the host permission so that it can trigger on [the url http://127.0.0.1:35001/](https://github.com/dougle/aws-vpn-tab-close/blob/main/manifest.json#L15)
